function DatasetInfo(handles)
	%
	% INPUTS:
	%   self:   Object,  Instance of the TestPlugin object
	%   handles:    struct, guidata structure from the DENSEanalysis
	%               GUI. This provides access to all data and controls 
	%               in the GUI.
	% Last Modified: 11:52 AM Monday, November 23, 2015
	% Modified By: Zhanqiu Liu (lafeir.lew@gmail.com)
	
	if isempty(handles.hdata)
		return
	end
	
	% fieldnames(handles.hdata.seq(2))
	if isempty(handles.hdata.seq(2).DENSEdata.EncFreq)
		EncFreq = zeros(0,0);
		for ii = 1:numel(handles.hdata.seq)
			EncFreq = [EncFreq handles.hdata.seq(2).DENSEdata.EncFreq];
		end
	else
		EncFreq = handles.hdata.seq(2).DENSEdata.EncFreq;
	end
	
	Age = datestr(datenum(handles.hdata.seq(2).StudyDate,'YYYYmmDD') - datenum(handles.hdata.seq(2).PatientBirthDate,'YYYYmmDD'),'mmDD');%'YYYYmmDD');

	datenum(handles.hdata.seq(2).PatientBirthDate,'YYYYmmDD');
	string = {'------Subject Info------',...
	strcat('Sex:', handles.hdata.seq(2).PatientSex),...
	strcat('BirthDate:', handles.hdata.seq(2).PatientBirthDate),...
	strcat('StudyDate:', handles.hdata.seq(2).StudyDate),...
	strcat('Age:', Age),...
	'------Scanning Properties------',...
	sprintf('EncFreq:%d ', EncFreq),...
	sprintf('ImagingFrequency:%d', handles.hdata.seq(2).ImagingFrequency),...
	sprintf('ImagingFrequency:%d', handles.hdata.seq(2).ImagingFrequency),...
	sprintf('MagneticFieldStrength:%d', handles.hdata.seq(2).MagneticFieldStrength),...
	strcat('PixelSpacing:',sprintf('%d ', handles.hdata.seq(2).PixelSpacing)),...
	sprintf('SliceThickness:%d', handles.hdata.seq(2).SliceThickness),...
	sprintf('RepetitionTime:%d', handles.hdata.seq(2).RepetitionTime),...
	sprintf('TriggerTime:%d', handles.hdata.seq(2).TriggerTime),...
	sprintf('EchoTime:%d', handles.hdata.seq(2).EchoTime),...
	sprintf('CardiacNumberOfImages:%d', handles.hdata.seq(2).CardiacNumberOfImages)};
	% sprintf('NominalInterval:%d', handles.hdata.seq(2).NominalInterval),...
	% sprintf('EchoNumber:%d', handles.hdata.seq(2).EchoNumber),...
	% sprintf('EchoTrainLength:%d', handles.hdata.seq(2).EchoTrainLength),...
	% sprintf('InversionTime:%d', handles.hdata.seq(2).InversionTime),...
	% sprintf(':%d', handles.hdata.seq(2).),...
	
	string{:}
	msgbox(string,'Important DatasetInfo');
end
