function HotkeysSummary(varargin)
% hObject    handle to HotkeysSummary (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
	% generate Report for Hotkeys
	%
	%
	% USAGE:
	%   self.HotkeysSummary()
	%
	% OUTPUTS;
	%           
	%
	% Last Modified: 11:52 AM Monday, November 23, 2015
	% Modified By: Zhanqiu Liu (lafeir.lew@gmail.com)

	%--- Hotkeys Entries ---%
	report={'<<<Keyboard>>>', ...
			'<Menu>', ...
			'Ctrl+Z => Undo', ...
			'Ctrl+C => Copy', ...
			'Ctrl+X => Cut', ...
			'Ctrl+V => Paste', ...
			'', ...
			'<Toolbar>', ...
			'E => Edit Contour', ...
			'Alt+D(Hold) => Data Cursor', ...
			'Plus => Zoom In', ...
			'Minus => Zoom Out', ...
			'Alt+P(Hold) => Pan', ...
			'Alt+C(Hold) => Adjust Contrast', ...
			'Alt+R(Hold) => 3d Rotation', ...
			'', ...
			'<Viewer>', ...
			'Numpad Number => Switch Slice', ...
			'Number => Switch Roi', ...
			'`(~) => No Roi', ...
			'Right Arrow/A => Next Phase', ...
			'Left Arrow/D => Previous Phase', ...
			'Up Arrow/W => Previous Tab', ...
			'Down Arrow/S => Next Tab', ...
			'Tab => Switch Tab/Viewer', ...
			'Space => Playback', ...
			'', ...
			'', ...
			'', ...
			'<<<Mouse>>>', ...
			'Left Click => Drag Points on a Contour', ...
			'Middle Click => Drag Contours', ...
			'Right Click => Context Menu/Confirm', ...
			'', ...
			'',};

	msgbox(report,'Summary of Hotkeys');

end